"use client";
import "./globals.css";
import { Inter } from "next/font/google";

// import GlobalProviders from "@/components/global-providers";0

import Nav from "@/components/nav";
import Sidebar from "@/components/sidebar";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
const [open,setOpen] =useState(false)
const handleClick = () => setOpen(!open)
console.log(open)
  return (
    <html lang="en">
      <body className={`${inter.className} h-full flex flex-col`}>
        <Nav handleClick={handleClick} />
        <main className="flex flex-row h-full relative">
          <Sidebar open={open}  />
          {children}
        </main>
      </body>
    </html>
  );
}
